export enum RAMO_ATIVIDADE {
  FABRICANTE = 'FABRICANTE',
  REVENDEDOR = 'REVENDEDOR',
  LOGÍSTICO = 'LOGÍSTICO',
  CONSUMIDOR = 'CONSUMIDOR',
}

export enum TIPO_ATIVIDADE {
  TRANSPORTE = 'TRANSPORTE',
  INCIDENTE = 'INCIDENTE',
  INSPEÇÃO = 'INSPEÇÃO',
  OUTRA_ATIVIDADE = 'OUTRA_ATIVIDADE',
  CONSUMO = 'CONSUMO',
}
export enum TIPO_TRANSPORTE {
  FABRICANTE = 'FABRICANTE',
  ARMAZÉM = 'ARMAZÉM',
  TRANSPORTE = 'TRANSPORTE',
}
